# Use the official Nginx image
FROM nginx:alpine

# Copy the HTML file to the Nginx server's default directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to access the web application
EXPOSE 80
