name: Build and Deploy Web Application

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app:project-333 Ansible/Docker_App_Ansible/
        docker push ${{ secrets.DOCKER_USERNAME }}/app:project-333

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job is completed before deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection and deploy to EC2
      run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > aws_key_333
          chmod 600 aws_key_333
          ssh -i aws_key_333 -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop project-333 || true
            docker rm project-333 || true
            docker run -d -p 80:80 --name project-333 ${{ secrets.DOCKER_USERNAME }}/app:project-333
          EOF
        
        